apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
  - protocol: TCP
    port: 85
    targetPort: 85
    nodePort: 30085
